// flow-typed signature: ff4619305edeaab321d8b42fa23faa6c
// flow-typed version: <<STUB>>/awilix_v^3.0.9/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'awilix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'awilix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'awilix/lib/awilix.browser' {
  declare module.exports: any;
}

declare module 'awilix/lib/awilix' {
  declare module.exports: any;
}

declare module 'awilix/lib/awilix.module' {
  declare module.exports: any;
}

declare module 'awilix/lib/awilix.umd' {
  declare module.exports: any;
}

declare module 'awilix/lib/container' {
  declare module.exports: any;
}

declare module 'awilix/lib/errors' {
  declare module.exports: any;
}

declare module 'awilix/lib/function-tokenizer' {
  declare module.exports: any;
}

declare module 'awilix/lib/injection-mode' {
  declare module.exports: any;
}

declare module 'awilix/lib/lifetime' {
  declare module.exports: any;
}

declare module 'awilix/lib/list-modules' {
  declare module.exports: any;
}

declare module 'awilix/lib/load-modules' {
  declare module.exports: any;
}

declare module 'awilix/lib/param-parser' {
  declare module.exports: any;
}

declare module 'awilix/lib/resolvers' {
  declare module.exports: any;
}

declare module 'awilix/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'awilix/lib/awilix.browser.js' {
  declare module.exports: $Exports<'awilix/lib/awilix.browser'>;
}
declare module 'awilix/lib/awilix.js' {
  declare module.exports: $Exports<'awilix/lib/awilix'>;
}
declare module 'awilix/lib/awilix.module.js' {
  declare module.exports: $Exports<'awilix/lib/awilix.module'>;
}
declare module 'awilix/lib/awilix.umd.js' {
  declare module.exports: $Exports<'awilix/lib/awilix.umd'>;
}
declare module 'awilix/lib/container.js' {
  declare module.exports: $Exports<'awilix/lib/container'>;
}
declare module 'awilix/lib/errors.js' {
  declare module.exports: $Exports<'awilix/lib/errors'>;
}
declare module 'awilix/lib/function-tokenizer.js' {
  declare module.exports: $Exports<'awilix/lib/function-tokenizer'>;
}
declare module 'awilix/lib/injection-mode.js' {
  declare module.exports: $Exports<'awilix/lib/injection-mode'>;
}
declare module 'awilix/lib/lifetime.js' {
  declare module.exports: $Exports<'awilix/lib/lifetime'>;
}
declare module 'awilix/lib/list-modules.js' {
  declare module.exports: $Exports<'awilix/lib/list-modules'>;
}
declare module 'awilix/lib/load-modules.js' {
  declare module.exports: $Exports<'awilix/lib/load-modules'>;
}
declare module 'awilix/lib/param-parser.js' {
  declare module.exports: $Exports<'awilix/lib/param-parser'>;
}
declare module 'awilix/lib/resolvers.js' {
  declare module.exports: $Exports<'awilix/lib/resolvers'>;
}
declare module 'awilix/lib/utils.js' {
  declare module.exports: $Exports<'awilix/lib/utils'>;
}
