// flow-typed signature: e1bc4ffdf40a12a240cfb2e630ecb515
// flow-typed version: <<STUB>>/koa-cookie_v^1.0.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-cookie/index' {
  declare module.exports: $Exports<'koa-cookie'>;
}
declare module 'koa-cookie/index.js' {
  declare module.exports: $Exports<'koa-cookie'>;
}
